# Generated by Django 3.1 on 2020-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_registermodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='num',
            field=models.IntegerField(verbose_name='Phone number'),
        ),
    ]
