# Generated by Django 3.1 on 2020-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_auto_20200830_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='is_block',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
