# Generated by Django 3.1 on 2020-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_registermodel_is_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
